Dir::Etc::sourcelist "/tmp/eda004c/apt/sources.list";
Dir::Etc::sourceparts "-";
Dir::State::lists "/tmp/eda004c/lists";
Dir::State::status "/tmp/eda004c/apt/status";
Dir::Cache::archives "/tmp/eda004c/archives";
Dir::Cache::pkgcache "/tmp/eda004c/apt/pkgcache.bin";
Dir::Cache::srcpkgcache "/tmp/eda004c/apt/srcpkgcache.bin";
APT::Sandbox::User "codespace";
Debug::NoLocking "true";
