import assert from "node:assert/strict"
import { mkdir, writeFile } from "node:fs/promises"
import path from "node:path"
import React from "react"
import { Circuit } from "@tscircuit/core"
import { CheckpointABoard } from "../src/spikes/native-hall/checkpoint-a"

const OUTPUT = path.resolve("tscircuit-native-checkpoint-a")
const TOLERANCE_MM = 0.001
const log: string[] = []
const note = (message: string) => {
  log.push(message)
  console.log(message)
}

type Element = Record<string, any>
const close = (actual: number, expected: number, label: string) =>
  assert.ok(
    Math.abs(actual - expected) <= TOLERANCE_MM,
    `${label}: expected ${expected}, received ${actual}`,
  )
const elementsOf = (json: Element[], type: string) =>
  json.filter((element) => element.type === type)

await mkdir(OUTPUT, { recursive: true })

const circuit = new Circuit()
circuit.add(<CheckpointABoard />)
await circuit.renderUntilSettled()
const circuitJson = circuit.getCircuitJson() as Element[]
await writeFile(
  path.join(OUTPUT, "circuit.json"),
  `${JSON.stringify(circuitJson, null, 2)}\n`,
)

const result: Record<string, string> = {
  checkpoint: "A",
  result: "FAIL",
  smdPads: "FAIL",
  platedHole: "FAIL",
  npth: "FAIL",
  pinMapping: "FAIL",
  duplicatePin3: "FAIL",
  alignment: "FAIL",
  topKeepout: "FAIL",
  bottomKeepout: "FAIL",
  copperPourExclusion: "FAIL",
  circuitJson: "generated by stock @tscircuit/core",
}

try {
  const pads = elementsOf(circuitJson, "pcb_smtpad")
  assert.equal(pads.length, 3)
  const expectedPads = [
    { hint: "1", x: -0.9375, y: -0.95 },
    { hint: "2", x: -0.9375, y: 0.95 },
    { hint: "3", x: 0.9375, y: 0 },
  ]
  for (const expected of expectedPads) {
    const pad = pads.find((candidate) => candidate.port_hints?.includes(expected.hint))
    assert.ok(pad, `missing SMT pad ${expected.hint}`)
    close(pad.x, expected.x, `SMT ${expected.hint} x`)
    close(pad.y, expected.y, `SMT ${expected.hint} y`)
    close(pad.width, 1.475, `SMT ${expected.hint} width`)
    close(pad.height, 0.6, `SMT ${expected.hint} height`)
    assert.equal(pad.layer, "top")
  }
  result.smdPads = "PASS: 3 native top-layer pads match within 0.001 mm"

  const plated = elementsOf(circuitJson, "pcb_plated_hole")
  assert.equal(plated.length, 1)
  close(plated[0].x, 2.3, "PTH x")
  close(plated[0].y, 0, "PTH y")
  close(plated[0].hole_diameter, 0.3, "PTH hole diameter")
  close(plated[0].outer_diameter, 0.6, "PTH outer diameter")
  assert.ok(plated[0].port_hints?.includes("3"))
  result.platedHole = "PASS: native pin-3 PTH geometry matches within 0.001 mm"

  const holes = elementsOf(circuitJson, "pcb_hole")
  assert.equal(holes.length, 2)
  for (const expectedX of [-5.08, 5.08]) {
    const hole = holes.find((candidate) => Math.abs(candidate.x - expectedX) <= TOLERANCE_MM)
    assert.ok(hole, `missing NPTH at ${expectedX}`)
    close(hole.y, 0, `NPTH ${expectedX} y`)
    close(hole.hole_diameter, 1.7, `NPTH ${expectedX} diameter`)
    assert.equal(hole.hole_shape, "circle")
  }
  result.npth = "PASS: 2 native circular NPTHs match within 0.001 mm"

  const sourcePorts = elementsOf(circuitJson, "source_port")
  for (const [pin, label] of [["1", "VCC"], ["2", "OUT"], ["3", "GND"]]) {
    const port = sourcePorts.find((candidate) =>
      String(candidate.pin_number) === pin || candidate.port_hints?.includes(pin),
    )
    assert.ok(port, `missing source port for pin ${pin}`)
    assert.ok(
      port.name === label || port.port_hints?.includes(label),
      `pin ${pin} does not carry label ${label}`,
    )
  }
  result.pinMapping = "PASS: DRV5055 DBZ 1=VCC, 2=OUT, 3=GND"

  const pad3 = pads.find((pad) => pad.port_hints?.includes("3"))!
  assert.ok(pad3.pcb_port_id)
  assert.equal(pad3.pcb_port_id, plated[0].pcb_port_id)
  result.duplicatePin3 = `PASS: shared pcb_port_id ${pad3.pcb_port_id}`
  result.alignment = "PASS: all six native features retain specified component-relative coordinates"

  const keepouts = elementsOf(circuitJson, "pcb_keepout")
  assert.equal(keepouts.length, 2)
  for (const layer of ["top", "bottom"]) {
    const keepout = keepouts.find(
      (candidate) => candidate.layers?.includes(layer) || candidate.layer === layer,
    )
    assert.ok(keepout, `missing ${layer} keepout`)
    close(keepout.center?.x ?? keepout.x, 0, `${layer} keepout x`)
    close(keepout.center?.y ?? keepout.y, 0, `${layer} keepout y`)
    close(keepout.width, 4, `${layer} keepout width`)
    close(keepout.height, 3.6, `${layer} keepout height`)
    assert.equal(keepout.allow_traces, true)
    assert.equal(keepout.allow_placements, true)
    result[`${layer}Keepout`] = "PASS: 4.0 x 3.6 mm copper-only exclusion"
  }

  const pours = elementsOf(circuitJson, "pcb_copper_pour")
  assert.equal(pours.length, 2)
  for (const layer of ["top", "bottom"]) {
    const pour = pours.find((candidate) => candidate.layer === layer)
    assert.ok(pour, `missing ${layer} copper pour`)
    assert.equal(pour.shape, "brep")
    assert.ok(pour.inner_rings?.length >= 1, `${layer} pour has no exclusion ring`)
    const ringAroundOrigin = pour.inner_rings.some((ring: any) => {
      const points: Array<{ x: number; y: number }> = Array.isArray(ring)
        ? ring
        : ring.vertices
      assert.ok(Array.isArray(points), "BRep inner ring has no vertices")
      const xs = points.map((point) => point.x)
      const ys = points.map((point) => point.y)
      return Math.min(...xs) <= -2 && Math.max(...xs) >= 2 && Math.min(...ys) <= -1.8 && Math.max(...ys) >= 1.8
    })
    assert.ok(ringAroundOrigin, `${layer} pour lacks keepout-envelope ring`)
  }
  result.copperPourExclusion = "PASS: both stock BRep pours contain the keepout-envelope inner ring"
  result.result = "PASS"
  note("Checkpoint A verification: PASS")
} catch (error) {
  result.result = "FAIL"
  note(`Checkpoint A verification: FAIL — ${error instanceof Error ? error.message : String(error)}`)
  throw error
} finally {
  const summary = {
    tolerance_mm: TOLERANCE_MM,
    smt_pads: 3,
    plated_holes: 1,
    mechanical_npth: 2,
    keepouts: { top: [4, 3.6], bottom: [4, 3.6] },
    fixture_board_mm: [16, 12],
  }
  await writeFile(path.join(OUTPUT, "verification-result.json"), `${JSON.stringify(result, null, 2)}\n`)
  await writeFile(path.join(OUTPUT, "geometry-summary.json"), `${JSON.stringify(summary, null, 2)}\n`)
  await writeFile(path.join(OUTPUT, "execution-log.txt"), `${log.join("\n")}\n`)
}
