import assert from "node:assert/strict"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import React from "react"
import { Circuit } from "@tscircuit/core"
import { M1FourKeyElectrical } from "../src/evaluation/m1-four-key"

type E=Record<string,any>
const circuit=new Circuit();circuit.add(<M1FourKeyElectrical/>);await circuit.renderUntilSettled()
const json=circuit.getCircuitJson() as E[], of=(t:string)=>json.filter(x=>x.type===t)
const components=of("source_component"),ports=of("source_port"),nets=of("source_net"),traces=of("source_trace")
const comp=(name:string)=>{const x=components.filter(c=>c.name===name);assert.equal(x.length,1,`${name} component count`);return x[0]}
const port=(c:E,name:string)=>{const x=ports.filter(p=>p.source_component_id===c.source_component_id&&p.name===name);assert.equal(x.length,1,`${c.name}.${name} port count`);return x[0]}
const net=(name:string)=>{const x=nets.filter(n=>n.name===name);assert.equal(x.length,1,`${name} net count`);return x[0]}
const connected=(cn:string,pn:string,nn:string)=>{const p=port(comp(cn),pn),n=net(nn);assert.ok(traces.some(t=>t.connected_source_port_ids?.includes(p.source_port_id)&&t.connected_source_net_ids?.includes(n.source_net_id)),`${cn}.${pn} -> ${nn}`)}
const results:Record<string,string>={};const check=(name:string,fn:()=>string)=>{try{results[name]=`PASS: ${fn()}`}catch(e){results[name]=`FAIL: ${e instanceof Error?e.message:e}`};console.log(`${name}: ${results[name]}`)}
const pinmap=await readFile(path.resolve("../sensor-test/pinmap.csv"),"utf8"),mcu=comp("U_MCU")
const physicalPins:Record<string,number>={IOVDD_1:1,MUX_A0:4,MUX_A1:5,MUX_A2:6,MUX_EN0:7,HALL_PWR_EN:9,IOVDD_10:10,STATUS_LED:14,TESTEN_19:19,XIN:20,XOUT:21,IOVDD_22:22,DVDD_23:23,SWCLK:24,SWDIO:25,RUN:26,IOVDD_33:33,ADC_SENSE:38,IOVDD_42:42,ADC_AVDD_43:43,VREG_IN_44:44,VREG_VOUT_45:45,USB_DM:46,USB_DP:47,USB_VDD_48:48,IOVDD_49:49,DVDD_50:50,QSPI_SD3:51,QSPI_SCLK:52,QSPI_SD0:53,QSPI_SD2:54,QSPI_SD1:55,QSPI_SS:56,GND_57:57}
check("rp2040PhysicalPins",()=>{for(const [name,pin] of Object.entries(physicalPins))assert.equal(port(mcu,name).pin_number,pin,`${name} physical pin`);return "authoritative RP2040 QFN-56 signal and supply pin numbers"})
check("pinmapLogicalAssignments",()=>{for(const [signal,gpio] of Object.entries({MUX_A0:"GPIO2",MUX_A1:"GPIO3",MUX_A2:"GPIO4",MUX_EN0:"GPIO5",HALL_PWR_EN:"GPIO7",STATUS_LED:"GPIO11",ADC_A:"GPIO26/ADC0",USB_DP:"USB_DP",USB_DM:"USB_DM",SWDIO:"SWDIO",SWCLK:"SWCLK",RUN:"RUN"}))assert.ok(pinmap.includes(`${signal},${gpio},`),`${signal} ${gpio}`);return "logical functions independently match pinmap.csv"})
check("rp2040Power",()=>{for(const p of ["IOVDD_1","IOVDD_10","IOVDD_22","IOVDD_33","IOVDD_42","IOVDD_49","USB_VDD_48","ADC_AVDD_43","VREG_IN_44"])connected("U_MCU",p,"V3V3");for(const p of ["VREG_VOUT_45","DVDD_23","DVDD_50"])connected("U_MCU",p,"V1V1");connected("U_MCU","TESTEN_19","GND");connected("U_MCU","GND_57","GND");return "all distinct IOVDD, DVDD, analog, USB, regulator, TESTEN, and exposed-pad connections"})
const caps:Record<string,[string,number]>={C_IOVDD1:["V3V3",100e-9],C_IOVDD10:["V3V3",100e-9],C_IOVDD22:["V3V3",100e-9],C_IOVDD33:["V3V3",100e-9],C_IOVDD42:["V3V3",100e-9],C_IOVDD49:["V3V3",100e-9],C_USB_VDD:["V3V3",100e-9],C_ADC_AVDD:["V3V3",100e-9],C_VREG_IN:["V3V3",1e-6],C_VREG_OUT:["V1V1",1e-6],C_DVDD23:["V1V1",100e-9],C_DVDD50:["V1V1",100e-9]}
check("rp2040Decoupling",()=>{for(const [c,[rail,value]] of Object.entries(caps)){assert.ok(Math.abs(comp(c).capacitance-value)<1e-12,`${c} value`);connected(c,"pin1",rail);connected(c,"pin2","GND")}return "official minimal-core supply groups have independently connected expected capacitors"})
check("crystal",()=>{assert.equal(comp("Y1").manufacturer_part_number,"ABM8-272-T3");assert.equal(port(mcu,"XIN").pin_number,20);assert.equal(port(mcu,"XOUT").pin_number,21);assert.equal(comp("R_XOUT").resistance,1000);assert.equal(comp("C_XIN").capacitance,15e-12);assert.equal(comp("C_XOUT").capacitance,15e-12);connected("U_MCU","XIN","XIN");connected("U_MCU","XOUT","XOUT");return "12MHz crystal, 15pF loads, and 1k XOUT series path terminate on pins 20/21"})
check("bootselQspi",()=>{assert.equal(port(mcu,"QSPI_SS").pin_number,56);connected("U_MCU","QSPI_SS","QSPI_SS_MCU");connected("R_QSPI_SS","pin1","QSPI_SS_MCU");connected("R_QSPI_SS","pin2","QSPI_SS_FLASH");connected("U_FLASH","CS","QSPI_SS_FLASH");connected("SW_BOOT","A","QSPI_SS_FLASH");connected("SW_BOOT","B","GND");assert.equal(comp("R_QSPI_SS").resistance,1000);return "RP2040 pin 56 -> 1k -> flash CS, BOOTSEL pulls flash side low"})
check("componentCounts",()=>{assert.equal(components.filter(c=>c.name.startsWith("U_H")).length,4);for(const x of ["J_USB","U_ESD","U_MCU","U_FLASH","Y1","U_LDO","U_LOAD","U_MUX"])comp(x);return "all required active blocks including four Hall sensors and USB ESD"})
check("partIdentity",()=>{const expected:Record<string,[string,string]>={U_MCU:["RP2040","C2040"],U_LDO:["AP2112K-3.3TRG1","C51118"],U_LOAD:["TPS22919DCKR","C2149796"],U_MUX:["TMUX1208PWR","C494728"],J_USB:["TYPE-C-31-M-12","C165948"],U_ESD:["USBLC6-2SC6","C7519"],U_H0:["DRV5055A3QDBZR","C266128"]};for(const [ref,[mpn,jlc]] of Object.entries(expected)){const c=comp(ref);assert.equal(c.manufacturer_part_number,mpn);assert.ok(c.supplier_part_numbers?.jlcpcb?.includes(jlc),`${ref} ${jlc}`)}return "all approved manufacturer and JLCPCB identities retained"})
check("hallMuxAdc",()=>{for(let i=0;i<4;i++){connected(`U_H${i}`,"VCC","HALL_5V");connected(`U_H${i}`,"OUT",`H${i}_RAW`);connected("U_MUX",`S${i+1}`,`H${i}_RAW`)}connected("U_MUX","D","MUX_D");connected("R_ADC_TOP","pin1","MUX_D");connected("R_ADC_TOP","pin2","ADC_SENSE");connected("R_ADC_BOTTOM","pin1","ADC_SENSE");connected("C_ADC","pin1","ADC_SENSE");connected("U_MCU","ADC_SENSE","ADC_SENSE");assert.equal(port(mcu,"ADC_SENSE").pin_number,38);assert.equal(comp("R_ADC_TOP").resistance,6800);assert.equal(comp("R_ADC_BOTTOM").resistance,10000);assert.equal(comp("C_ADC").capacitance,1e-9);return "S1-S4 mapping and MUX_D -> 6.8k/10k/1nF ADC_SENSE -> physical pin 38"})
check("tmuxSpares",()=>{for(const n of [5,6,7,8]){connected("U_MUX",`S${n}`,`MUX_S${n}`);connected(`TP_MUX_S${n}`,"pin1",`MUX_S${n}`)}return "S5-S8 each terminate at a labeled extension test point"})
check("loadSwitchDecoupling",()=>{for(const [c,rail] of [["C_LOAD_IN","VBUS"],["C_LOAD_OUT","HALL_5V"]]){assert.equal(comp(c).capacitance,1e-6);connected(c,"pin1",rail);connected(c,"pin2","GND")}return "TPS22919 IN and OUT each have established 1uF local decoupling"})
check("runTestPoint",()=>{connected("U_MCU","RUN","RUN");connected("SW_RUN","A","RUN");connected("TP_RUN","pin1","RUN");return "RUN pin 26, reset button, and TP_RUN share RUN"})
check("usbSemantics",()=>{for(const p of ["A4_B9","A9_B4"])connected("J_USB",p,"VBUS");for(const p of ["A1_B12","A12_B1"])connected("J_USB",p,"GND");for(const p of ["A6","B6"])connected("J_USB",p,"USB_DP_CONN");for(const p of ["A7","B7"])connected("J_USB",p,"USB_DM_CONN");for(const p of ["A8","B8"])assert.equal(port(comp("J_USB"),p).do_not_connect,true,`${p} explicit NC`);return "Type-C named contacts preserve VBUS/GND pairs, A6/B6 D+, A7/B7 D-, CC and explicit SBU NC ports"})
check("usbEsdPath",()=>{assert.equal(comp("U_ESD").manufacturer_part_number,"USBLC6-2SC6");assert.ok(comp("U_ESD").supplier_part_numbers.jlcpcb.includes("C7519"));connected("U_ESD","IO1_1","USB_DP_CONN");connected("U_ESD","IO1_2","USB_DP_ESD");connected("R_USB_DP","pin1","USB_DP_ESD");connected("R_USB_DP","pin2","USB_DP");connected("U_ESD","IO2_1","USB_DM_CONN");connected("U_ESD","IO2_2","USB_DM_ESD");connected("R_USB_DM","pin1","USB_DM_ESD");connected("R_USB_DM","pin2","USB_DM");return "connector -> USBLC6-2SC6 exact feedthrough pins -> 27ohm -> RP2040 for D+/D-"})
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<=0.001,`${a} != ${b}`)
check("usbGeometry",()=>{const c=comp("J_USB"),pc=of("pcb_component").find(x=>x.source_component_id===c.source_component_id),pads=of("pcb_smtpad").filter(x=>x.pcb_component_id===pc.pcb_component_id),holes=of("pcb_plated_hole").filter(x=>x.pcb_component_id===pc.pcb_component_id),npth=of("pcb_hole").filter(x=>x.pcb_component_id===pc.pcb_component_id);const expected:Record<string,[number,number]>={A1_B12:[-3.2,.6],A4_B9:[-2.4,.6],A5:[-1.25,.3],A6:[-.75,.3],A7:[-.25,.3],A8:[.25,.3],B8:[.75,.3],B7:[1.25,.3],B6:[1.75,.3],B5:[2.25,.3],A9_B4:[2.4,.6],A12_B1:[3.2,.6]};assert.equal(pads.length,12);const byHint=(id:string)=>{const p=pads.find(x=>x.port_hints?.includes(id));assert.ok(p,`${id} land`);return p},left=byHint("A1_B12"),right=byHint("A12_B1"),axisX=(left.x+right.x)/2,contactY=left.y,sign=Math.sign(left.x-axisX)/-1;for(const [id,[x,w]] of Object.entries(expected)){const p=byHint(id);close(p.x-axisX,sign*x);close(p.y,contactY);close(Math.min(p.width,p.height),w);close(Math.max(p.width,p.height),1.15)}assert.equal(holes.length,4);assert.deepEqual(holes.map(x=>[x.hole_width,x.hole_height,x.outer_width,x.outer_height]),[[.6,1.7,1,2.1],[.6,1.7,1,2.1],[.6,1.4,1,1.8],[.6,1.4,1,1.8]]);for(const h of holes)close(Math.abs(h.x-axisX),4.32);assert.deepEqual(holes.map(h=>Number(Math.abs(h.y-contactY).toFixed(2))).sort((a,b)=>a-b),[.35,.35,5.55,5.55]);assert.equal(npth.length,2);for(const h of npth){close(h.hole_diameter,.65);close(Math.abs(h.x-axisX),2.89);close(Math.abs(h.y-contactY),3.1)}close(Math.abs(npth[0].x-npth[1].x),5.78);return "manufacturer contact coordinates/dimensions, four distinct plated shell stakes, and two 0.65mm NPTHs"})
check("hallGrid",()=>{const pts=[0,1,2,3].map(i=>{const c=comp(`U_H${i}`);return of("pcb_component").find(x=>x.source_component_id===c.source_component_id).center});close(Math.abs(pts[1].x-pts[0].x),17);close(Math.abs(pts[2].y-pts[0].y),17);close(Math.abs(pts[3].x-pts[2].x),17);close(Math.abs(pts[3].y-pts[1].y),17);return "explicit 2x2 switch centers have 17.0mm horizontal and vertical pitch"})
check("testPoints",()=>{for(const n of ["VBUS","HALL_5V","H0_RAW","H1_RAW","H2_RAW","H3_RAW","MUX_D","ADC_SENSE","GND","SWDIO","SWCLK","RUN"])connected(`TP_${n}`,"pin1",n);connected("TP_3V3","pin1","V3V3");return "all required measurement points resolve to actual source traces/nets"})
const errors=json.filter(x=>["source_failed_to_create_component_error","source_trace_not_connected_error","source_pin_must_be_connected_error","pcb_missing_footprint_error"].includes(x.type));check("electricalErrors",()=>{assert.equal(errors.length,0,JSON.stringify(errors));return "missing-footprint=0; electrical-errors=0"})
const failed=Object.values(results).filter(x=>x.startsWith("FAIL")),out=path.resolve("tscircuit-m1-electrical");await mkdir(out,{recursive:true});await writeFile(path.join(out,"circuit.json"),JSON.stringify(json,null,2)+"\n");await writeFile(path.join(out,"verification-result.json"),JSON.stringify({result:failed.length?"FAIL":"PASS",results,missing_footprint_count:of("pcb_missing_footprint_error").length,electrical_error_count:errors.length,design_data_gaps:["passive supplier part numbers","LED/button/test-point supplier part numbers"]},null,2)+"\n");if(failed.length)process.exitCode=1
