import assert from "node:assert/strict"
import { mkdir, writeFile } from "node:fs/promises"
import path from "node:path"
import React from "react"
import { Circuit } from "@tscircuit/core"
import { CheckpointBBoard } from "../src/spikes/native-hall/checkpoint-b"

type Element = Record<string, any>
const OUTPUT = path.resolve("tscircuit-native-checkpoint-b")
const CAPACITANCE_TOLERANCE_F = 1e-12
const log: string[] = []

const circuit = new Circuit()
circuit.add(<CheckpointBBoard />)
await circuit.renderUntilSettled()
const circuitJson = circuit.getCircuitJson() as Element[]
const elementsOf = (type: string) => circuitJson.filter((element) => element.type === type)

await mkdir(OUTPUT, { recursive: true })
await writeFile(path.join(OUTPUT, "circuit.json"), `${JSON.stringify(circuitJson, null, 2)}\n`)

const mandatoryCategories = [
  "hallSensorCount",
  "requiredNets",
  "hallPinMapping",
  "hallPinAttributes",
  "hallVccConnectivity",
  "hallGroundConnectivity",
  "hallOutConnectivity",
  "duplicatePin3",
  "decouplingCapacitor",
  "decouplingConnectivity",
  "capacitorFootprint",
  "rawTestPoint",
  "testPointConnectivity",
  "sourceElectricalErrors",
] as const
type Category = (typeof mandatoryCategories)[number]
const result: Record<string, string> = {
  checkpoint: "B",
  result: "FAIL",
  circuitJson: "PASS: generated by stock @tscircuit/core",
  ...Object.fromEntries(mandatoryCategories.map((category) => [category, "FAIL: not run"])),
}
const verify = (category: Category, check: () => string) => {
  try {
    result[category] = `PASS: ${check()}`
  } catch (error) {
    result[category] = `FAIL: ${error instanceof Error ? error.message : String(error)}`
  }
  log.push(`${category}: ${result[category]}`)
  console.log(`${category}: ${result[category]}`)
}

const components = elementsOf("source_component")
const ports = elementsOf("source_port")
const nets = elementsOf("source_net")
const traces = elementsOf("source_trace")
const component = (name: string, ftype: string) => {
  const matches = components.filter((item) => item.name === name && item.ftype === ftype)
  assert.equal(matches.length, 1, `${name}/${ftype} count`)
  return matches[0]
}
const port = (owner: Element, name: string) => {
  const matches = ports.filter(
    (item) => item.source_component_id === owner.source_component_id && item.name === name,
  )
  assert.equal(matches.length, 1, `${owner.name}.${name} source port count`)
  return matches[0]
}
const net = (name: string) => {
  const matches = nets.filter((item) => item.name === name)
  assert.equal(matches.length, 1, `${name} source net count`)
  return matches[0]
}
const traceConnects = (name: string, sourcePort: Element, sourceNet: Element) => {
  const matches = traces.filter((item) => item.name === name)
  assert.equal(matches.length, 1, `${name} source trace count`)
  const trace = matches[0]
  assert.ok(trace.connected_source_port_ids?.includes(sourcePort.source_port_id), `${name} lacks source port`)
  assert.ok(trace.connected_source_net_ids?.includes(sourceNet.source_net_id), `${name} lacks source net`)
  return trace
}

const hall = component("U1", "simple_chip")
const capacitor = component("C_HALL1", "simple_capacitor")
const testPoint = component("TP_H0_RAW", "simple_test_point")
const hallVcc = port(hall, "VCC")
const hallOut = port(hall, "OUT")
const hallGnd = port(hall, "GND")
const capacitorPin1 = port(capacitor, "pin1")
const capacitorPin2 = port(capacitor, "pin2")
const testPointPin1 = port(testPoint, "pin1")
const hall5V = net("HALL_5V")
const ground = net("GND")
const hallRaw = net("H0_RAW")

verify("hallSensorCount", () => {
  assert.equal(components.filter((item) => item.name === "U1").length, 1)
  return "exactly one U1 source component with ftype simple_chip"
})
verify("requiredNets", () => {
  assert.equal(hall5V.is_power, true, "HALL_5V is_power")
  assert.equal(ground.is_ground, true, "GND is_ground")
  return "unique HALL_5V power, GND ground, and H0_RAW source nets"
})
verify("hallPinMapping", () => {
  assert.equal(hallVcc.pin_number, 1)
  assert.equal(hallOut.pin_number, 2)
  assert.equal(hallGnd.pin_number, 3)
  return "U1 primary pins are 1=VCC, 2=OUT, 3=GND"
})
verify("hallPinAttributes", () => {
  assert.equal(hallVcc.requires_power, true)
  assert.equal(hallVcc.must_be_connected, true)
  assert.equal(hallVcc.should_have_decoupling_capacitor, true)
  assert.equal(hallVcc.recommended_decoupling_capacitor_capacitance, "100nF")
  assert.equal(hallOut.must_be_connected, true)
  assert.equal(hallGnd.requires_ground, true)
  assert.equal(hallGnd.must_be_connected, true)
  return "stock source_port power, ground, connection, and 100nF decoupling attributes"
})
verify("hallVccConnectivity", () => {
  traceConnects("HALL_VCC_TO_HALL_5V", hallVcc, hall5V)
  return "HALL_VCC_TO_HALL_5V resolves U1.VCC to HALL_5V"
})
verify("hallGroundConnectivity", () => {
  traceConnects("HALL_GND_TO_GND", hallGnd, ground)
  return "HALL_GND_TO_GND resolves U1.GND to GND"
})
verify("hallOutConnectivity", () => {
  traceConnects("HALL_OUT_TO_H0_RAW", hallOut, hallRaw)
  return "HALL_OUT_TO_H0_RAW resolves U1.OUT to H0_RAW"
})
verify("duplicatePin3", () => {
  const internalPort = ports.find(
    (item) => item.source_component_id === hall.source_component_id && item.name === "pin3_internal_1",
  )
  assert.ok(internalPort, "secondary physical pin 3 source port missing")
  const connection = elementsOf("source_component_internal_connection").find(
    (item) => item.source_component_id === hall.source_component_id &&
      item.source_port_ids?.includes(hallGnd.source_port_id) &&
      item.source_port_ids?.includes(internalPort.source_port_id),
  )
  assert.ok(connection, "primary and secondary pin 3 internal connection missing")
  return "secondary PTH pin 3 is internally connected to primary U1.GND"
})
verify("decouplingCapacitor", () => {
  assert.ok(Math.abs(capacitor.capacitance - 100e-9) <= CAPACITANCE_TOLERANCE_F)
  return "one C_HALL1 simple_capacitor is 100nF within 1e-12F"
})
verify("decouplingConnectivity", () => {
  traceConnects("C_HALL1_TO_HALL_5V", capacitorPin1, hall5V)
  traceConnects("C_HALL1_TO_GND", capacitorPin2, ground)
  return "C_HALL1.pin1 -> HALL_5V and pin2 -> GND"
})
const pcbComponents = elementsOf("pcb_component")
const pcbPads = elementsOf("pcb_smtpad")
const pcbComponentFor = (source: Element) => {
  const matches = pcbComponents.filter((item) => item.source_component_id === source.source_component_id)
  assert.equal(matches.length, 1, `${source.name} PCB component count`)
  return matches[0]
}
verify("capacitorFootprint", () => {
  const pcb = pcbComponentFor(capacitor)
  assert.equal(pcbPads.filter((pad) => pad.pcb_component_id === pcb.pcb_component_id).length, 2)
  return "stock 0603 footprint generated one PCB component and two SMT pads"
})
verify("rawTestPoint", () => {
  assert.equal(testPoint.footprint_variant, "pad")
  assert.equal(testPoint.pad_shape, "circle")
  assert.equal(testPoint.pad_diameter, 1.2)
  const pcb = pcbComponentFor(testPoint)
  assert.ok(pcbPads.some((pad) => pad.pcb_component_id === pcb.pcb_component_id))
  return "TP_H0_RAW circular 1.2mm pad generated with at least one SMT pad"
})
verify("testPointConnectivity", () => {
  traceConnects("TP_H0_RAW_TO_H0_RAW", testPointPin1, hallRaw)
  traceConnects("HALL_OUT_TO_H0_RAW", hallOut, hallRaw)
  return "U1.OUT and TP_H0_RAW.pin1 both resolve to H0_RAW via named source traces"
})
const electricalErrorTypes = [
  "source_failed_to_create_component_error",
  "source_trace_not_connected_error",
  "source_pin_must_be_connected_error",
  "pcb_missing_footprint_error",
]
const electricalErrors = circuitJson.filter((item) => electricalErrorTypes.includes(item.type))
verify("sourceElectricalErrors", () => {
  assert.equal(electricalErrors.length, 0, JSON.stringify(electricalErrors))
  return `${electricalErrorTypes.join(", ")} count = 0`
})

const failedCategories = mandatoryCategories.filter((category) => !result[category].startsWith("PASS:"))
result.result = failedCategories.length === 0 ? "PASS" : "FAIL"
log.push(`Checkpoint B verification: ${result.result}`)
console.log(`Checkpoint B verification: ${result.result}`)
const summary = {
  hall_sensor_count: components.filter((item) => item.name === "U1" && item.ftype === "simple_chip").length,
  nets: { HALL_5V: hall5V.is_power, GND: ground.is_ground, H0_RAW: true },
  capacitor: { capacitance_f: capacitor.capacitance, footprint: "0603", smt_pad_count: 2 },
  test_point: { footprint_variant: testPoint.footprint_variant, pad_shape: testPoint.pad_shape, pad_diameter_mm: testPoint.pad_diameter },
  source_electrical_error_count: electricalErrors.length,
  routing_disabled: true,
}
await writeFile(path.join(OUTPUT, "verification-result.json"), `${JSON.stringify(result, null, 2)}\n`)
await writeFile(path.join(OUTPUT, "electrical-summary.json"), `${JSON.stringify(summary, null, 2)}\n`)
await writeFile(path.join(OUTPUT, "execution-log.txt"), `${log.join("\n")}\n`)
if (failedCategories.length > 0) {
  console.error(`Mandatory categories failed: ${failedCategories.join(", ")}`)
  process.exitCode = 1
}
