import assert from "node:assert/strict"
import { mkdir, writeFile } from "node:fs/promises"
import path from "node:path"
import React from "react"
import { Circuit } from "@tscircuit/core"
import { CheckpointABoard } from "../src/spikes/native-hall/checkpoint-a"

const OUTPUT = path.resolve("tscircuit-native-checkpoint-a")
const TOLERANCE_MM = 0.001
const log: string[] = []
type Element = Record<string, any>

const circuit = new Circuit()
circuit.add(<CheckpointABoard />)
await circuit.renderUntilSettled()
const circuitJson = circuit.getCircuitJson() as Element[]
const elementsOf = (type: string) =>
  circuitJson.filter((element) => element.type === type)
const close = (actual: number, expected: number, label: string) =>
  assert.ok(
    Number.isFinite(actual) && Math.abs(actual - expected) <= TOLERANCE_MM,
    `${label}: expected ${expected}, received ${actual}`,
  )

await mkdir(OUTPUT, { recursive: true })
await writeFile(
  path.join(OUTPUT, "circuit.json"),
  `${JSON.stringify(circuitJson, null, 2)}\n`,
)

const mandatoryCategories = [
  "smdPads",
  "platedHole",
  "npth",
  "pinMapping",
  "duplicatePin3",
  "alignment",
  "sourceRenderErrors",
  "topKeepout",
  "bottomKeepout",
  "topCopperPour",
  "bottomCopperPour",
  "copperPourExclusion",
] as const
const result: Record<string, string> = {
  checkpoint: "A",
  result: "FAIL",
  circuitJson: "PASS: generated by stock @tscircuit/core",
  ...Object.fromEntries(mandatoryCategories.map((category) => [category, "FAIL: not run"])),
}

const verify = (category: (typeof mandatoryCategories)[number], check: () => string) => {
  try {
    result[category] = `PASS: ${check()}`
  } catch (error) {
    result[category] = `FAIL: ${error instanceof Error ? error.message : String(error)}`
  }
  log.push(`${category}: ${result[category]}`)
  console.log(`${category}: ${result[category]}`)
}

const pads = elementsOf("pcb_smtpad")
const plated = elementsOf("pcb_plated_hole")
const holes = elementsOf("pcb_hole")
const sourcePorts = elementsOf("source_port")
const pcbPorts = elementsOf("pcb_port")
const expectedPads = [
  { hint: "1", x: -0.9375, y: -0.95 },
  { hint: "2", x: -0.9375, y: 0.95 },
  { hint: "3", x: 0.9375, y: 0 },
]
const padFor = (hint: string) => {
  const pad = pads.find((candidate) => candidate.port_hints?.includes(hint))
  assert.ok(pad, `missing SMT pad ${hint}`)
  return pad
}

verify("smdPads", () => {
  assert.equal(pads.length, 3, "Hall sensor must produce exactly three SMT pads")
  for (const expected of expectedPads) {
    const pad = padFor(expected.hint)
    close(pad.x, expected.x, `SMT ${expected.hint} x`)
    close(pad.y, expected.y, `SMT ${expected.hint} y`)
    close(pad.width, 1.475, `SMT ${expected.hint} width`)
    close(pad.height, 0.6, `SMT ${expected.hint} height`)
    assert.equal(pad.layer, "top")
  }
  return "3 native top-layer pads match within 0.001 mm"
})

verify("platedHole", () => {
  assert.equal(plated.length, 1, "expected exactly one plated hole")
  close(plated[0].x, 2.3, "PTH x")
  close(plated[0].y, 0, "PTH y")
  close(plated[0].hole_diameter, 0.3, "PTH hole diameter")
  close(plated[0].outer_diameter, 0.6, "PTH outer diameter")
  assert.ok(plated[0].port_hints?.includes("3"), "PTH lacks port hint 3")
  return "native pin-3 PTH geometry matches within 0.001 mm"
})

verify("npth", () => {
  assert.equal(holes.length, 2, "expected exactly two NPTHs")
  for (const expectedX of [-5.08, 5.08]) {
    const hole = holes.find((candidate) => Math.abs(candidate.x - expectedX) <= TOLERANCE_MM)
    assert.ok(hole, `missing NPTH at x=${expectedX}`)
    close(hole.y, 0, `NPTH ${expectedX} y`)
    close(hole.hole_diameter, 1.7, `NPTH ${expectedX} diameter`)
    assert.equal(hole.hole_shape, "circle")
  }
  return "2 native circular NPTHs match within 0.001 mm"
})

verify("pinMapping", () => {
  for (const [pin, label] of [["1", "VCC"], ["2", "OUT"], ["3", "GND"]]) {
    const port = sourcePorts.find((candidate) => String(candidate.pin_number) === pin)
    assert.ok(port, `missing primary source port for pin ${pin}`)
    assert.equal(port.name, label, `pin ${pin} label`)
  }
  return "DRV5055 DBZ primary pins are 1=VCC, 2=OUT, 3=GND"
})

verify("duplicatePin3", () => {
  const smd3 = padFor("3")
  assert.equal(plated.length, 1, "expected exactly one plated hole")
  assert.ok(smd3.pcb_port_id, "SMD pin 3 lacks pcb_port_id")
  assert.ok(plated[0].pcb_port_id, "PTH pin 3 lacks pcb_port_id")
  const smdPcbPort = pcbPorts.find((port) => port.pcb_port_id === smd3.pcb_port_id)
  const pthPcbPort = pcbPorts.find((port) => port.pcb_port_id === plated[0].pcb_port_id)
  assert.ok(smdPcbPort?.source_port_id, "SMD pin 3 PCB port lacks source_port_id")
  assert.ok(pthPcbPort?.source_port_id, "PTH pin 3 PCB port lacks source_port_id")
  assert.notEqual(smdPcbPort.pcb_port_id, pthPcbPort.pcb_port_id)

  const smdSourcePort = sourcePorts.find(
    (port) => port.source_port_id === smdPcbPort.source_port_id,
  )
  const pthSourcePort = sourcePorts.find(
    (port) => port.source_port_id === pthPcbPort.source_port_id,
  )
  assert.ok(smdSourcePort && pthSourcePort, "could not resolve both pin 3 source ports")
  assert.equal(smdSourcePort.pin_number, 3)
  assert.equal(smdSourcePort.name, "GND")
  assert.equal(pthSourcePort.source_component_id, smdSourcePort.source_component_id)

  const connection = elementsOf("source_component_internal_connection").find(
    (candidate) =>
      candidate.source_port_ids?.includes(smdSourcePort.source_port_id) &&
      candidate.source_port_ids?.includes(pthSourcePort.source_port_id),
  )
  assert.ok(connection, "no internal connection contains both pin 3 source ports")
  assert.equal(connection.source_component_id, smdSourcePort.source_component_id)
  return "separate physical PCB ports are internally connected by stock tscircuit source_component_internal_connection"
})

verify("alignment", () => {
  for (const expected of expectedPads) {
    const pad = padFor(expected.hint)
    close(pad.x, expected.x, `SMT ${expected.hint} alignment x`)
    close(pad.y, expected.y, `SMT ${expected.hint} alignment y`)
  }
  assert.equal(plated.length, 1, "expected PTH3 for alignment")
  close(plated[0].x, 2.3, "PTH3 alignment x")
  close(plated[0].y, 0, "PTH3 alignment y")
  for (const expectedX of [-5.08, 5.08]) {
    const hole = holes.find((candidate) => Math.abs(candidate.x - expectedX) <= TOLERANCE_MM)
    assert.ok(hole, `missing NPTH alignment point at x=${expectedX}`)
    close(hole.x, expectedX, `NPTH alignment x=${expectedX}`)
    close(hole.y, 0, `NPTH alignment y at x=${expectedX}`)
  }
  return "all six generated feature positions independently match within 0.001 mm"
})

verify("sourceRenderErrors", () => {
  const errors = elementsOf("source_failed_to_create_component_error")
  assert.equal(errors.length, 0, JSON.stringify(errors))
  return "source_failed_to_create_component_error count = 0"
})

const keepouts = elementsOf("pcb_keepout")
for (const layer of ["top", "bottom"] as const) {
  verify(`${layer}Keepout`, () => {
    assert.equal(keepouts.length, 2, "expected exactly two PCB keepouts")
    const keepout = keepouts.find((candidate) => candidate.layers?.includes(layer))
    assert.ok(keepout, `missing ${layer} keepout`)
    close(keepout.center?.x, 0, `${layer} keepout x`)
    close(keepout.center?.y, 0, `${layer} keepout y`)
    close(keepout.width, 4, `${layer} keepout width`)
    close(keepout.height, 3.6, `${layer} keepout height`)
    assert.equal(keepout.allow_traces, true)
    assert.equal(keepout.allow_placements, true)
    return "4.0 x 3.6 mm copper-only exclusion at (0, 0)"
  })
}

const pours = elementsOf("pcb_copper_pour")
const exclusionRingFor = (layer: "top" | "bottom") => {
  assert.equal(pours.length, 2, "expected exactly two PCB copper pours")
  const pour = pours.find((candidate) => candidate.layer === layer)
  assert.ok(pour, `missing ${layer} copper pour`)
  assert.equal(pour.shape, "brep")
  const rings = pour.brep_shape?.inner_rings
  assert.ok(rings?.length >= 1, `${layer} BRep pour has no inner rings`)
  const ring = rings.find((candidate: Element) => {
    const points: Array<{ x: number; y: number }> = candidate.vertices
    if (!Array.isArray(points)) return false
    const xs = points.map((point) => point.x)
    const ys = points.map((point) => point.y)
    return (
      Math.min(...xs) <= -2 + TOLERANCE_MM &&
      Math.max(...xs) >= 2 - TOLERANCE_MM &&
      Math.min(...ys) <= -1.8 + TOLERANCE_MM &&
      Math.max(...ys) >= 1.8 - TOLERANCE_MM
    )
  })
  assert.ok(ring, `${layer} pour lacks a ring spanning the keepout envelope`)
  return ring
}

for (const layer of ["top", "bottom"] as const) {
  verify(`${layer}CopperPour`, () => {
    exclusionRingFor(layer)
    return `stock ${layer} BRep pour generated with keepout exclusion ring`
  })
}
verify("copperPourExclusion", () => {
  exclusionRingFor("top")
  exclusionRingFor("bottom")
  return "both stock BRep pours contain a ring spanning the 4.0 x 3.6 mm keepout envelope"
})

const failedCategories = mandatoryCategories.filter(
  (category) => !result[category].startsWith("PASS:"),
)
result.result = failedCategories.length === 0 ? "PASS" : "FAIL"
log.push(`Checkpoint A verification: ${result.result}`)
console.log(`Checkpoint A verification: ${result.result}`)

const summary = {
  tolerance_mm: TOLERANCE_MM,
  smt_pads: pads.length,
  plated_holes: plated.length,
  mechanical_npth: holes.length,
  source_render_errors: elementsOf("source_failed_to_create_component_error").length,
  keepouts: { top: [4, 3.6], bottom: [4, 3.6] },
  copper_pours: pours.length,
  fixture_board_mm: [16, 12],
}
await writeFile(path.join(OUTPUT, "verification-result.json"), `${JSON.stringify(result, null, 2)}\n`)
await writeFile(path.join(OUTPUT, "geometry-summary.json"), `${JSON.stringify(summary, null, 2)}\n`)
await writeFile(path.join(OUTPUT, "execution-log.txt"), `${log.join("\n")}\n`)

if (failedCategories.length > 0) {
  console.error(`Mandatory categories failed: ${failedCategories.join(", ")}`)
  process.exitCode = 1
}
