Dir::Etc::sourcelist "/tmp/eda004e/apt/sources.list";
Dir::Etc::sourceparts "-";
Dir::State::lists "/tmp/eda004e/lists";
Dir::State::status "/tmp/eda004e/apt/status";
Dir::Cache::archives "/tmp/eda004e/archives";
Dir::Cache::pkgcache "/tmp/eda004e/apt/pkgcache.bin";
Dir::Cache::srcpkgcache "/tmp/eda004e/apt/srcpkgcache.bin";
APT::Sandbox::User "codespace";
Debug::NoLocking "true";
